services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=ControleDeSalaFEMASSDb;User Id=sa;Password=Your_password123;Encrypt=false;TrustServerCertificate=true;"
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver